version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - "__pycache__/"
            - "*.pyc"
        - action: rebuild
          path: requirements.txt
    depends_on:
      - migration

  migration:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    command: python manage.py migrate
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY} 